// config/index.tsx
import { cookieStorage, createStorage } from "wagmi";
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi";
import { bsc, bscTestnet } from "@reown/appkit/networks";
import type { Chain } from "viem";

// Read Project ID from environment variables
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID;

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error(
    "NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local"
  );
}

// Define supported networks for VAI Protocol, explicitly typed as a non-empty array of Chains
export const networks: [Chain, ...Chain[]] = [
  bsc, // BSC Mainnet for VAI token
  bscTestnet, // BSC Testnet for development
];

// Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({
    storage: cookieStorage,
  }),
  ssr: true,
  projectId,
  networks,
});

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig;
